[package]
name = "metered-macro"
version = "0.1.0"
authors = ["Simon Chemouil <simon.chemouil@lambdacube.fr>"]
edition = "2018"

[dependencies]
syn = {version= "0.15.26", features = ["full"] }
synattra = { path ="../../synattra", version = "0.1.0"}
aspect-weave = { path ="../../aspect-rs/aspect-weave", version = "0.1.0"}
quote = "0.6.11"
proc-macro2 = "0.4.26"
heck = "0.3.1"
indexmap = "1.0.2"


[lib]
proc-macro = true