[package]
name = "metered"
version = "0.1.0"
authors = ["Simon Chemouil <simon.chemouil@lambdacube.fr>"]
edition = "2018"

[dependencies]
aspect = { path = "../../aspect-rs/aspect-core", version = "0.1.0"}
hdrhistogram = "6.1.1"
metered-macro = { path = "../metered-macro", version = "0.1.0" }
atomic = "0.4"
atomic_refcell = "0.1.3"
serde = { version = "1.0", features = ["derive"] }


[features]
# no features by default
default = []

# Use the serde feature to make metered' types implement Serialize
serialize = []